### ISSUE TITLE
How to Use bot 

### ISSUE THREAD

**Issue by Pearboy** [iholston/lol-bot#85]
So the script is working but doesn’t seem to be working right in game. Items don’t buy and i’m getting 0 farm. My character is being directed to random or their spawn. Help pls

**Comment by iholston** [comment]
What does your setup look like. the bot only attack moves down lane so it should be getting some farm. is this window showing up as 1024x768?

**Comment by Pearboy** [comment]
I changed my window to 1024x768 after seeing this comment and everything works except buying items. The mouse is a bit to low when trying to click the purchase button which results in nothing happening

**Comment by iholston** [comment]
Yea well, I'm not sure why your window was not the correct size to begin with. The bot should be changing all your settings so your shop window will probably be not in the correct place either. I'm releasing a new version of the bot probably tomorrow that will be able to buy items regardless of the shop window. In the meantime, just move the shop so that it lines up with the purchase button.

**Comment by Pearboy** [comment]
Gotchu. Thanks for the tip
